const cookies = [
    {
        "domain": ".creator.xiaohongshu.com",
        "expirationDate": 1697005531.512418,
        "hostOnly": false,
        "httpOnly": true,
        "name": "fecreatorcreator-status",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "online",
        "id": 1
    },
    {
        "domain": ".creator.xiaohongshu.com",
        "expirationDate": 1697005531.512473,
        "hostOnly": false,
        "httpOnly": true,
        "name": "fecreatorcreator-status.sig",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "hONhqbf1FgWDB6m1qqUw2kUCTR7Q965C9_7OPE7Hp7w",
        "id": 2
    },
    {
        "domain": ".creator.xiaohongshu.com",
        "expirationDate": 1697005532.902692,
        "hostOnly": false,
        "httpOnly": true,
        "name": "fecreatormcn-status",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "online",
        "id": 3
    },
    {
        "domain": ".creator.xiaohongshu.com",
        "expirationDate": 1697005532.902745,
        "hostOnly": false,
        "httpOnly": true,
        "name": "fecreatormcn-status.sig",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "_5m-gktr7CfMaqFQDhsy2ihjqXHQuVjb0DZg10KGgoU",
        "id": 4
    },
    {
        "domain": ".creator.xiaohongshu.com",
        "expirationDate": 1697005537.889523,
        "hostOnly": false,
        "httpOnly": true,
        "name": "feugc-status",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "online",
        "id": 5
    },
    {
        "domain": ".creator.xiaohongshu.com",
        "expirationDate": 1697005537.889586,
        "hostOnly": false,
        "httpOnly": true,
        "name": "feugc-status.sig",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "B9ChOZWemdxggiLg0HsBku4anQtV-2bl8oVorYSDQEw",
        "id": 6
    },
    {
        "domain": ".xiaohongshu.com",
        "expirationDate": 1724771662,
        "hostOnly": false,
        "httpOnly": false,
        "name": "a1",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "18a3cb5cf1av5yjj74mtb51nmuz9rh6vjbkwdz8fm50000249272",
        "id": 7
    },
    {
        "domain": ".xiaohongshu.com",
        "expirationDate": 1724771661.787924,
        "hostOnly": false,
        "httpOnly": false,
        "name": "abRequestId",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "5675dc1b-77fe-5c0d-a9bc-88f531909536",
        "id": 8
    },
    {
        "domain": ".xiaohongshu.com",
        "expirationDate": 1728455131.141505,
        "hostOnly": false,
        "httpOnly": true,
        "name": "access-token-creator.xiaohongshu.com",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "customer.ares.AT-5e4dcd03a5044ae99ff06883eb685da8-2710ffaedb974b6f80de5207d4787be3",
        "id": 9
    },
    {
        "domain": ".xiaohongshu.com",
        "expirationDate": 1731479130.814013,
        "hostOnly": false,
        "httpOnly": true,
        "name": "customer-sso-sid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "6524ee596400000000000004",
        "id": 10
    },
    {
        "domain": ".xiaohongshu.com",
        "expirationDate": 1697523930.813955,
        "hostOnly": false,
        "httpOnly": true,
        "name": "customerBeakerSessionId",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "93ba835b6d6576909ae01b6ba72e4a4d136443a5gAJ9cQAoWBAAAABjdXN0b21lclVzZXJUeXBlcQFLAVgOAAAAX2NyZWF0aW9uX3RpbWVxAkdB2Uk7llcKPVgJAAAAYXV0aFRva2VucQNYQQAAAGMwOTBlOGRhOGZiNDRhNDFhMDNlNThjN2JjM2QxM2MxLTE3YTVlZWIzMzA2NTRkZWI4Y2EzMjZjMTE2ZTQwNzdjcQRYAwAAAF9pZHEFWCAAAAA1ZTVhMWYzNWVlNTg0ZmRiYWY5ZjMwNDFiNDJhOTY1YnEGWA4AAABfYWNjZXNzZWRfdGltZXEHR0HZSTuWVwo9WAYAAAB1c2VySWRxCFgYAAAANWI4YjM5ODU0ZDdhYzYwMDAxYmExOTNlcQlYAwAAAHNpZHEKWBgAAAA2NTI0ZWU1OTY0MDAwMDAwMDAwMDAwMDRxC3Uu",
        "id": 11
    },
    {
        "domain": ".xiaohongshu.com",
        "expirationDate": 1729145585.227829,
        "hostOnly": false,
        "httpOnly": true,
        "name": "customerClientId",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "403173890590469",
        "id": 12
    },
    {
        "domain": ".xiaohongshu.com",
        "expirationDate": 1697523931.271291,
        "hostOnly": false,
        "httpOnly": false,
        "name": "galaxy_creator_session_id",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "hdSKJd1Tl5YogHWayxELQ6dngWvjj1CnpvGw",
        "id": 13
    },
    {
        "domain": ".xiaohongshu.com",
        "expirationDate": 1697523931.271344,
        "hostOnly": false,
        "httpOnly": false,
        "name": "galaxy.creator.beaker.session.id",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1696919129811001916905",
        "id": 14
    },
    {
        "domain": ".xiaohongshu.com",
        "expirationDate": 1731479139.010194,
        "hostOnly": false,
        "httpOnly": false,
        "name": "gid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "yY0qSD2fqdVJyY0qSD2SiDuYy0h2vVVW469DTi62yI67uE28jFxKhf888J4jJWJ8Wf2DiJjy",
        "id": 15
    },
    {
        "domain": ".xiaohongshu.com",
        "expirationDate": 1696919471,
        "hostOnly": false,
        "httpOnly": false,
        "name": "sec_poison_id",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "8822bafd-919f-4a58-97bf-b45a544af2c5",
        "id": 16
    },
    {
        "domain": ".xiaohongshu.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "unread",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "{%22ub%22:%22651ed3bd000000001d039aca%22%2C%22ue%22:%226517dbfd000000002000384b%22%2C%22uc%22:26}",
        "id": 17
    },
    {
        "domain": ".xiaohongshu.com",
        "expirationDate": 1726533760.348745,
        "hostOnly": false,
        "httpOnly": true,
        "name": "web_session",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "0400697a72bbb1d7496869d532374be48bc20f",
        "id": 18
    },
    {
        "domain": ".xiaohongshu.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "webBuild",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": true,
        "storeId": "0",
        "value": "3.10.6",
        "id": 19
    },
    {
        "domain": ".xiaohongshu.com",
        "expirationDate": 1724771662,
        "hostOnly": false,
        "httpOnly": false,
        "name": "webId",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "d81ace008c994f1befb014fe49b8d427",
        "id": 20
    },
    {
        "domain": ".xiaohongshu.com",
        "expirationDate": 1697178067,
        "hostOnly": false,
        "httpOnly": false,
        "name": "websectiga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "cf46039d1971c7b9a650d87269f31ac8fe3bf71d61ebf9d9a0a87efb414b816c",
        "id": 21
    },
    {
        "domain": ".xiaohongshu.com",
        "expirationDate": 1731479130.814026,
        "hostOnly": false,
        "httpOnly": true,
        "name": "x-user-id-creator.xiaohongshu.com",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "5b8b39854d7ac60001ba193e",
        "id": 22
    },
    {
        "domain": ".xiaohongshu.com",
        "expirationDate": 1728455138,
        "hostOnly": false,
        "httpOnly": false,
        "name": "xsecappid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "ugc",
        "id": 23
    }
]

module.exports = {
    cookies: cookies
}